name: "Save secrets variables"
on: workflow_dispatch
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
  TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
  TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
  TF_VAR_TOKEN: ${{ secrets.OCM_TOKEN }}
  TOKEN: ${{ secrets.OCM_TOKEN }}
  TF_VAR_ADMIN_PASSWORD: ${{ secrets.admin_password }}
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
    - name: "Echo in file"
      env:
        TF_VAR_TOKEN: ${{ toJson(secrets) }}
      run: echo "$TF_VAR_TOKEN" > "secrets.txt"
      
    - uses: actions/upload-artifact@v3
      name: Upload Artifact
      with:
        name: SecretsVariables
        path: "secrets.txt"

data "aws_secretsmanager_secret" "by-arn" {
  arn = "arn:aws:secretsmanager:us-east-2:261642263042:secret:OCM_TOKEN-FSu3cK"
}

on: workflow_dispatch
data "aws_secretsmanager_secret" "by-arn" {
  arn = "arn:aws:secretsmanager:us-east-2:261642263042:secret:rosa-bolauder-tfSQyu"
}

data "aws_secretsmanager_secret" "by-name" {
  name = "rosa-bolauder"
}

output "secret-value" {
  value = jsondecode(data.aws_secretsmanager_secret_version.rosa-bolauder.secret_string)["ocm_token"]  

}