
name: rosa-create-with-vpc-dev
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

on: workflow_dispatch
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
  TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
  TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
  TF_VAR_TOKEN: ${{ secrets.token }}
  TF_VAR_ADMIN_PASSWORD: ${{ secrets.admin_password }}


jobs:
  rosa-create-with-vpc:
    name: init-plan-apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Init
        id: init
        run: terraform init -backend-config=backend.tfvars
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file=dev.tfvars -lock=false
      
      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve -lock=false
